### PR TITLE
Add pandas and scikit-learn to the math tag

### PR DESCRIPTION
**Pull request by jaguarfi**
# Description

Add pandas and scikit-learn to the math tag

# Testing

I search for compatibility issues but I did not found anything, I also created the image locally and it worked. I also ran the image with the [mdm](https://version.aalto.fi/gitlab/course/mdm) course and I did not found any problem. Of course, I was not able to use working solutions. But, there were no errors related to the image itself.

# Have you updated the README or other relevant documentation?

Yes

# Is it [Done](https://wiki.aalto.fi/display/EDIT/Definition+of+Done)?

*Clean up your git commit history before submitting the pull request!*

- [ ] I (developer) have created unit tests and the tests pass
- [ ] I (developer) have created functional tests (Selenium tests) if applicable
- [X] I (developer) have tested the changes manually
- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

### CODE REVIEW

**Comment by raphendyr** [comment]
I recommend to consider creating a machine learning layer on top of the math layer. Might be easier to manage dependencies in the future. Starting a new Dockerfile with `FROM apluslms/grade-python:math-$FULL_TAG` and adding the new name in https://github.com/apluslms/grade-python/blob/master/hooks/build#L24 should do the trick.

However, this adds one more tag which might make usage more complicated, so it's not definitely the best option.

**Comment by Mankro** [comment]
> I recommend to consider creating a machine learning layer on top of the math layer. Might be easier to manage dependencies in the future. Starting a new Dockerfile with `FROM apluslms/grade-python:math-$FULL_TAG` and adding the new name in https://github.com/apluslms/grade-python/blob/master/hooks/build#L24 should do the trick.
> 
> However, this adds one more tag which might make usage more complicated, so it's not definitely the best option.

@jaguarfi Let's take @raphendyr 's advice into account and create a new layer called `ml` (machine learning) that is based on the `math` layer. Let's not modify the existing `math` layer then.

**Review by Mankro — CHANGES_REQUESTED** [review]
This looks good, but let's make a new layer based on the discussion.

**Review by Mankro — APPROVED** [review]
Great!

**Pull request merged**
